"""empty message

Revision ID: 31536c7fdf8b
Revises: 
Create Date: 2022-06-26 14:44:43.094981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31536c7fdf8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(precision=4), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ingredients', sa.String(length=240), nullable=False),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('img_url', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredients'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dish')
    # ### end Alembic commands ###
